# Generated by Django 3.2.4 on 2021-10-29 10:26

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='posts/default.jpeg', null=True, upload_to=posts.models.rename_and_path),
        ),
    ]
